sudo: required
dist: trusty
language: bash

services:
    - docker

before_install:
    - docker pull ubuntu:16.04
    - docker build -t magicicada-server-test-run .

script:
    - docker run magicicada-server-test-run make test SOURCEDEPS_DIR=sourcedeps
