[tool.black]
line-length = 79
skip-string-normalization = true
exclude = '''
/(
    \.git
  | .env
  | .sourcecode
  | lib/magicicadaclient
  | lib/dirspec
  | magicicada/filesync/migrations
  | magicicada/txlog/migrations
)/
'''
