# Generated by Django 1.9 on 2016-03-07 19:00


from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBWorkerLastRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DBWorkerUnseen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.UUIDField(null=True)),
                ('volume_id', models.UUIDField(null=True)),
                ('owner_id', models.BigIntegerField()),
                ('op_type', models.CharField(choices=[('user_created', 'user_created'), ('delete', 'delete'), ('move', 'move'), ('put_content', 'put_content'), ('share_accepted', 'share_accepted'), ('share_deleted', 'share_deleted'), ('public_access_changed', 'public_access_changed'), ('udf_created', 'udf_created'), ('udf_deleted', 'udf_deleted')], max_length=256)),
                ('path', models.TextField(null=True)),
                ('generation', models.BigIntegerField(null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('mimetype', models.TextField(null=True)),
                ('extra_data', models.TextField(null=True)),
                ('old_path', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dbworkerlastrow',
            name='txlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='txlog.TransactionLog'),
        ),
    ]
