# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-10 13:33
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesync', '0002_custom-sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
