# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-22 15:37
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesync', '0003_auto_20220510_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentblob',
            old_name='hash',
            new_name='_hash',
        ),
        migrations.RenameField(
            model_name='contentblob',
            old_name='magic_hash',
            new_name='_magic_hash',
        ),
        migrations.RenameField(
            model_name='resumableupload',
            old_name='hash_context',
            new_name='_hash_context',
        ),
        migrations.RenameField(
            model_name='resumableupload',
            old_name='magic_hash_context',
            new_name='_magic_hash_context',
        ),
        migrations.RenameField(
            model_name='uploadjob',
            old_name='hash_hint',
            new_name='_hash_hint',
        ),
        migrations.AlterField(
            model_name='storageuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
