# Generated by Django 2.2.28 on 2022-08-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesync', '0004_auto_20220722_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageuser',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=150, verbose_name='last name'
            ),
        ),
    ]
