# Generated by Django 3.2.15 on 2022-08-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesync', '0005_auto_20220830_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
