#! /bin/bash
#
# Copyright 2012-2013 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# In addition, as a special exception, the copyright holders give
# permission to link the code of portions of this program with the
# OpenSSL library under certain conditions as described in each
# individual source file, and distribute linked combinations
# including the two.
# You must obey the GNU General Public License in all respects
# for all of the code used other than OpenSSL.  If you modify
# file(s) with this exception, you may extend this exception to your
# version of the file(s), but you are not obligated to do so.  If you
# do not wish to do so, delete this exception statement from your
# version.  If you delete this exception statement from all source
# files in the program, then also delete it here.

PROXY_TESTS_PATH="ubuntuone/proxy/tests"

# Allow alternative python executable via environment variable.  This is
# useful for virtualenv testing.
PYTHON=${PYTHON:-'python'}

set -e
if [ $# -ne 0 ]; then
    # run specific module given by the caller
    MODULE="$@"
else
    # run all tests, useful for tarmac and reviews
    MODULE="ubuntuone"
fi

SYSNAME=`uname -s`

if [ "$SYSNAME" == "Darwin" ]; then
    IGNORE_FILES="test_linux.py,test_windows.py"
    IGNORE_PATHS="ubuntuone/platform/tests/linux"
    REACTOR=qt4
else
    # Linux
    IGNORE_FILES="test_darwin.py,test_fsevents_daemon.py,test_windows.py"
    IGNORE_PATHS="ubuntuone/platform/tests/windows"
    REACTOR=gi
fi

echo "*** Running test suite for ""$MODULE"" ***"
export SSL_CERTIFICATES_DIR=/etc/ssl/certs
$PYTHON ./setup.py build
u1trial --reactor=$REACTOR -i "$IGNORE_FILES" -p "$IGNORE_PATHS,$PROXY_TESTS_PATH" "$MODULE"
echo "*** Running tests for ubuntuone-client-proxy ***"
u1trial --reactor=qt4 -i "$IGNORE_FILES" -p "$IGNORE_PATHS" "$PROXY_TESTS_PATH"
$PYTHON ./setup.py clean
rm -rf _trial_temp
rm -rf build

$PYTHON contrib/check-reactor-import
