.TH SDTOOL 1
.SH NAME
u1sdtool \- command line utility for controlling ubuntuone-syncdaemon
.SH SYNOPSYS
.B u1sdtool
[\fIOPTION\fR]... [\fIARGS\fR]
.br
.B u1sdtool
\-\-wait
.br
.B u1sdtool
\-\-accept-share=SHARE_ID
.br
.B u1sdtool
\-\-reject-share=SHARE_ID
.br
.B u1sdtool
\-\-list-shares
.br
.B u1sdtool
\-\-refresh-shares
.br
.B u1sdtool
\-\-offer-share PATH USER SHARE_NAME ACCESS_LEVEL
.br
.B u1sdtool
\-\-list-shared
.br
.B u1sdtool
\-\-create-folder=PATH
.br
.B u1sdtool
\-\-delete-folder=FOLDER_ID
.br
.B u1sdtool
\-\-list-folders
.br
.B u1sdtool
\-\-subscribe-folder=FOLDER_ID
.br
.B u1sdtool
\-\-unsubscribe-folder=FOLDER_ID
.br
.B u1sdtool
\-\-refresh-volumes
.br
.B u1sdtool
\-\-rescan-from-scratch=VOLUME_ID
.br
.B u1sdtool
\-\-info=PATH
.br
.B u1sdtool
\-\-list-dirty-nodes
.br
.B u1sdtool
\-\-current-transfers
.br
.B u1sdtool
\-\-quit
.br
.B u1sdtool
\-\-connect
.br
.B u1sdtool
\-\-disconnect
.br
.B u1sdtool
\-\-status
.br
.B u1sdtool
\-\-waiting
.br
.B u1sdtool
\-\-waiting-metadata
.br
.B u1sdtool
\-\-waiting-content
.br
.B u1sdtool
\-\-start

.SH DESCRIPTION
u1sdtool is a command line utility for controlling ubuntuone-syncdaemon.
It can be used to get information about the metadata of ubuntuone-syncdaemon 
but also to create shares, accept or reject offered shares and to force a 
refresh on the list of shares.
.PP
.SH OPTIONS
.TP
\fB\-\-wait\fR
Wait until ubuntuone-syncdaemon reachs nirvana
.TP
\fB\-\-accept-share\fR=\fISHARE_ID\fR
Accept the share with the specified id
.RS
.TP
.I SHARE_ID
The share id, as returned by \-\-list-shares
.RE
.TP
\fB\-\-reject-share\fR=\fISHARE_ID\fR
Reject the share with the specified id
.RS
.TP
.I SHARE_ID
The share id, as returned by \-\-list-shares
.RE
.TP
\fB\-\-list-shares\fR
Get the list of shares
.TP
\fB\-\-refresh-shares\fR
request a refresh of the list of shares to the server
.TP
\fB\-\-offer-share\fR=\fIPATH\fR \fIUSER\fR \fISHARE_NAME\fR \fIACCESS_LEVEL\fR
share PATH to USER.
.RS
.TP
.I PATH
A path of a directory or file managed by ubuntuone-syncdaemon (can't be a path inside a Share)
.TP
.I USER
The (short) username, that this share is going to be offered
.TP
.I SHARE_NAME
The share name, as it's going to be offered to USER
.TP
.I ACCESS_LEVEL
The acces level of USER to this share, can be: "View" or "Modify"
.RE
.TP
\fB\-\-list-shared\fR
List the shared paths/shares offered.
.TP
\fB\-\-create-folder\fR=\fIPATH\fR
Create user defined folder in the specified path
.RS
.TP
.I PATH
The path of a directory to be managed by ubuntuone-syncdaemon
.RE
.TP
\fB\-\-delete-folder\fR=\fIFOLDER_ID\fR
Delete user defined folder identified by FOLDER_ID
.RS
.TP
.I FOLDER_ID
The folder id, as returned by --list-folders
.RE
.TP
\fB\-\-list-folders\fR
List all the user defined folders
.RE
.TP
\fB\-\-subscribe-folder\fR=\fIFOLDER_ID\fR
Subscribe to the user defined folder specified by FOLDER_ID
.RS
.TP
.I FOLDER_ID
The folder id, as returned by --list-folders
.RE
.TP
\fB\-\-unsubscribe-folder\fR=\fIFOLDER_ID\fR
Unsubscribe from the user defined folder specified by FOLDER_ID
.RS
.TP
.I FOLDER_ID
The folder id, as returned by --list-folders
.RE
.TP
\fB\-\-refresh-volumes\fR
Request a refresh of the list of volumes to the server
.TP
\fB\-\-rescan-from-scratch\fR=\fIVOLUME_ID\fR
Request a rescan from scratch for a volume.
.RS
.TP
.I VOLUME_ID
The volume id, as returned by --list-folders or --list-shares
.RE
.TP
\fB\-\-info\fR=\fIPATH\fR
Request the metadata of PATH
.RS
.TP
.I PATH
A path of a directory or file managed by ubuntuone-syncdaemon
.RE
.TP
\fB\-\-list-dirty-nodes\fR
Show the list of nodes marked as 'dirty'
.TP
\fB\-\-current-transfers\fR
Show the current uploads and downloads
.TP
\fB\-\-quit\fR
Shutdown ubuntuone-syncdaemon
.TP
\fB\-\-connect\fR
Connect the syncdaemon
.TP
\fB\-\-disconnect\fR
Disconnect the syncdaemon
.TP
\fB\-\-status\fR
Get the current status of syncdaemon
.TP
\fB\-\-waiting\fR
Get the operations being executed.
.TP
\fB\-\-waiting-metadata\fR
Get the waiting metadata list (NOTE: This option is deprecated and will go away shortly)
.TP
\fB\-\-waiting-content\fR
Get the waiting content list (NOTE: This option is deprecated and will go away shortly)
.RS
.TP
.I SHARE_ID
The share id, as returned by \-\-waiting
.TP
.I NODE_ID
The node id, as returned by \-\-waiting
.RE
.TP
\fB\-\-free-space\fR=\fIVOLUME_ID\fR
Get the free space for a volume.
.RS
.TP
.I VOLUME_ID
The volume id, as returned by --list-folders or --list-shares
.RE
.TP
\fB\-\-start\fR
Start syncdaemon if it's not running

.SH AUTHOR
This manual page was written by Guillermo Gonzalez <guillermo.gonzalez@canonical.com>.

